apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: jsch
  annotations:
    github.com/project-slug: lemra-org/jsch
spec:
  type: other
  lifecycle: unknown
  owner: user:development/guest
